def get_awareness_content():
    return {
        "tips": [
            {
                "id": "passwords",
                "icon": "LockKeyhole",
                "title": "Use Strong Passwords",
                "description": "Create unique passwords with at least 12 characters including numbers, symbols, and mixed case letters.",
            },
            {
                "id": "two-factor",
                "icon": "KeyRound",
                "title": "Enable Two-Factor Authentication",
                "description": "Add an extra layer of security by enabling 2FA on all your important accounts.",
            },
            {
                "id": "phishing",
                "icon": "Mail",
                "title": "Beware of Phishing",
                "description": "Do not click suspicious links or download attachments from unknown senders.",
            },
            {
                "id": "network",
                "icon": "Wifi",
                "title": "Secure Your Network",
                "description": "Use WPA3 encryption for WiFi and avoid using public networks for sensitive tasks.",
            },
            {
                "id": "updates",
                "icon": "Smartphone",
                "title": "Keep Software Updated",
                "description": "Regularly update your operating system and applications to patch security vulnerabilities.",
            },
            {
                "id": "backups",
                "icon": "ShieldCheck",
                "title": "Backup Your Data",
                "description": "Create regular backups of important files and store them in multiple secure locations.",
            },
        ],
        "threats": [
            {
                "id": "phishing-attacks",
                "icon": "TriangleAlert",
                "title": "Phishing Attacks",
                "badge": "High",
                "tone": "high",
                "description": "Fraudulent emails or messages designed to steal your credentials or personal information.",
                "howToAvoid": [
                    "Verify sender email addresses carefully",
                    "Do not click on suspicious links",
                    "Check for spelling and grammar errors",
                    "Contact the company directly if unsure",
                ],
            },
            {
                "id": "malware-ransomware",
                "icon": "Bug",
                "title": "Malware & Ransomware",
                "badge": "Critical",
                "tone": "critical",
                "description": "Malicious software that can damage your system or encrypt your files for ransom.",
                "howToAvoid": [
                    "Install reputable antivirus software",
                    "Do not download from untrusted sources",
                    "Keep your system updated",
                    "Backup important files regularly",
                ],
            },
            {
                "id": "social-engineering",
                "icon": "Zap",
                "title": "Social Engineering",
                "badge": "Medium",
                "tone": "medium",
                "description": "Manipulating people into revealing confidential information or performing actions.",
                "howToAvoid": [
                    "Be skeptical of unexpected requests",
                    "Verify identity before sharing info",
                    "Do not share passwords or codes",
                    "Trust your instincts",
                ],
            },
            {
                "id": "weak-passwords",
                "icon": "Smartphone",
                "title": "Weak Passwords",
                "badge": "Low",
                "tone": "low",
                "description": "Using simple or reused passwords makes your accounts vulnerable to attacks.",
                "howToAvoid": [
                    "Use password managers",
                    "Create unique passwords per account",
                    "Use passphrases instead of passwords",
                    "Enable multi-factor authentication",
                ],
            },
        ],
        "resources": [
            {
                "id": "password-guide",
                "icon": "FileText",
                "type": "Article",
                "topic": "Basics",
                "title": "Complete Guide to Password Security",
                "description": "Everything you need to know about creating and managing secure passwords.",
                "duration": "8 min read",
                "url": "https://www.cisa.gov/secure-our-world/use-strong-passwords",
            },
            {
                "id": "phishing-video",
                "icon": "Video",
                "type": "Video",
                "topic": "Threats",
                "title": "Understanding Phishing Attacks",
                "description": "Learn to identify and avoid phishing attempts with real examples.",
                "duration": "12 min",
                "url": "https://www.youtube.com/results?search_query=cisa+phishing+awareness",
            },
            {
                "id": "two-factor-guide",
                "icon": "BookOpen",
                "type": "Guide",
                "topic": "Basics",
                "title": "Setting Up Two-Factor Authentication",
                "description": "Step-by-step guide to enable 2FA on popular platforms.",
                "duration": "5 min read",
                "url": "https://www.cisa.gov/secure-our-world/turn-mfa",
            },
            {
                "id": "ransomware-article",
                "icon": "FileText",
                "type": "Article",
                "topic": "Threats",
                "title": "Ransomware: Prevention and Recovery",
                "description": "How to protect against ransomware and what to do if infected.",
                "duration": "10 min read",
                "url": "https://www.cisa.gov/stopransomware",
            },
            {
                "id": "network-video",
                "icon": "Video",
                "type": "Video",
                "topic": "Network",
                "title": "Secure Your Home Network",
                "description": "Best practices for securing your WiFi and home devices.",
                "duration": "15 min",
                "url": "https://www.youtube.com/results?search_query=secure+home+network+cybersecurity",
            },
            {
                "id": "social-guide",
                "icon": "BookOpen",
                "type": "Guide",
                "topic": "Threats",
                "title": "Social Engineering Tactics",
                "description": "Recognize and defend against social engineering attacks.",
                "duration": "7 min read",
                "url": "https://www.cisa.gov/news-events/news/avoiding-social-engineering-and-phishing-attacks",
            },
        ],
        "downloads": [
            {
                "id": "checklist",
                "title": "Security Awareness Checklist",
                "description": "Daily security practices checklist",
                "fileMeta": "PDF | generated instantly",
                "sections": [
                    "Use unique passwords and a password manager.",
                    "Turn on MFA for email, banking, admin, and cloud accounts.",
                    "Verify sender identity before opening links or attachments.",
                    "Keep operating systems, browsers, and apps updated.",
                    "Back up important files and test recovery periodically.",
                ],
            },
            {
                "id": "incident-plan",
                "title": "Incident Response Plan Template",
                "description": "Template for handling security incidents",
                "fileMeta": "PDF | generated instantly",
                "sections": [
                    "Identify the affected asset, user, account, and timestamp.",
                    "Preserve logs, screenshots, alerts, and suspicious files.",
                    "Contain the incident by disabling accounts or isolating devices.",
                    "Notify the correct owner, manager, or security contact.",
                    "Document root cause, impact, remediation, and lessons learned.",
                ],
            },
            {
                "id": "password-managers",
                "title": "Password Manager Comparison",
                "description": "Compare popular password managers",
                "fileMeta": "PDF | generated instantly",
                "sections": [
                    "Prefer managers with strong encryption and independent audits.",
                    "Check MFA support, recovery options, and device sync controls.",
                    "Use sharing features only for team-approved secrets.",
                    "Review breach alerts and password health dashboards monthly.",
                    "Export recovery codes and store them securely offline.",
                ],
            },
        ],
    }
