def get_awareness_content():
    return {
        "tips": [
            {
                "id": "passwords",
                "icon": "LockKeyhole",
                "title": "Strengthen Passwords",
                "description": "Use unique passphrases with 12+ characters and a mix of symbols, numbers, and letter cases.",
            },
            {
                "id": "two-factor",
                "icon": "KeyRound",
                "title": "Enable Multi-Factor Authentication",
                "description": "Turn on MFA for accounts that support it to reduce account takeover risk.",
            },
            {
                "id": "phishing",
                "icon": "Mail",
                "title": "Verify Messages Before Acting",
                "description": "Treat unexpected links, attachments, and login prompts as suspicious until verified.",
            },
            {
                "id": "network",
                "icon": "Wifi",
                "title": "Secure Network Access",
                "description": "Prefer WPA3, segment sensitive devices, and avoid public Wi-Fi for critical work.",
            },
            {
                "id": "updates",
                "icon": "Smartphone",
                "title": "Keep Systems Updated",
                "description": "Apply operating system and application updates promptly to reduce known exposure.",
            },
            {
                "id": "backups",
                "icon": "ShieldCheck",
                "title": "Maintain Backups",
                "description": "Keep validated backups offline or in protected storage and test recovery regularly.",
            },
        ],
        "threats": [
            {
                "id": "phishing-attacks",
                "icon": "TriangleAlert",
                "title": "Phishing Attacks",
                "badge": "High",
                "tone": "high",
                "description": "Messages that impersonate trusted senders to steal credentials or trigger unsafe actions.",
                "howToAvoid": [
                    "Verify the sender through a known channel",
                    "Inspect URLs before clicking",
                    "Watch for urgency and pressure tactics",
                    "Escalate uncertain messages to security",
                ],
            },
            {
                "id": "malware-ransomware",
                "icon": "Bug",
                "title": "Malware & Ransomware",
                "badge": "Critical",
                "tone": "critical",
                "description": "Malicious code that can disrupt systems, steal data, or encrypt files for ransom.",
                "howToAvoid": [
                    "Use reputable endpoint protection",
                    "Avoid untrusted downloads and extensions",
                    "Patch systems and browsers quickly",
                    "Keep offline recovery copies available",
                ],
            },
            {
                "id": "social-engineering",
                "icon": "Zap",
                "title": "Social Engineering",
                "badge": "Medium",
                "tone": "medium",
                "description": "Psychological manipulation used to bypass controls and extract sensitive information.",
                "howToAvoid": [
                    "Validate unusual requests independently",
                    "Confirm identity before sharing information",
                    "Never disclose passwords or OTPs",
                    "Escalate anything that feels off",
                ],
            },
            {
                "id": "weak-passwords",
                "icon": "Smartphone",
                "title": "Weak Passwords",
                "badge": "Low",
                "tone": "low",
                "description": "Simple or reused passwords make account compromise much easier.",
                "howToAvoid": [
                    "Use a password manager",
                    "Create unique credentials per account",
                    "Prefer long passphrases",
                    "Enable MFA wherever possible",
                ],
            },
        ],
        "resources": [
            {
                "id": "password-guide",
                "icon": "FileText",
                "type": "Article",
                "topic": "Basics",
                "audience": "Individuals",
                "priority": "Foundation",
                "title": "Password Security Guide",
                "description": "Best practices for creating, storing, and rotating high-value credentials.",
                "duration": "8 min read",
                "url": "https://www.cisa.gov/secure-our-world/use-strong-passwords",
                "takeaways": [
                    "Build long passphrases that are easy to remember and hard to guess.",
                    "Use a password manager instead of reusing credentials across services.",
                    "Rotate only when risk changes or credentials are exposed.",
                ],
                "bestFor": "New users, admins, and anyone managing multiple accounts.",
                "nextSteps": [
                    "Audit reused passwords",
                    "Turn on MFA for sensitive accounts",
                    "Move credentials into a password manager",
                ],
            },
            {
                "id": "phishing-video",
                "icon": "Video",
                "type": "Video",
                "topic": "Threats",
                "audience": "Teams",
                "priority": "High leverage",
                "title": "Phishing Detection Guide",
                "description": "Recognize common lures and respond safely to suspicious messages.",
                "duration": "12 min",
                "url": "https://www.youtube.com/results?search_query=cisa+phishing+awareness",
                "takeaways": [
                    "Spot urgency, impersonation, and mismatched links fast.",
                    "Pause before opening attachments or approving logins.",
                    "Report suspicious messages early so others do not get hit.",
                ],
                "bestFor": "Front-line staff, support teams, and phishing drills.",
                "nextSteps": [
                    "Run a mock phishing exercise",
                    "Review sender domains before clicking",
                    "Create a reporting shortcut for the team",
                ],
            },
            {
                "id": "two-factor-guide",
                "icon": "BookOpen",
                "type": "Guide",
                "topic": "Basics",
                "audience": "All users",
                "priority": "Essential",
                "title": "MFA Setup Guide",
                "description": "Enable multi-factor authentication across the services you rely on most.",
                "duration": "5 min read",
                "url": "https://www.cisa.gov/secure-our-world/turn-mfa",
                "takeaways": [
                    "Pick app-based or hardware-based factors over SMS when possible.",
                    "Protect the account that secures your recovery options first.",
                    "Store backup codes somewhere secure and reachable.",
                ],
                "bestFor": "Account owners, IT admins, and onboarding sessions.",
                "nextSteps": [
                    "Enable MFA on email first",
                    "Save recovery codes offline",
                    "Test a backup login method",
                ],
            },
            {
                "id": "ransomware-article",
                "icon": "FileText",
                "type": "Article",
                "topic": "Threats",
                "audience": "Operations",
                "priority": "Critical",
                "title": "Ransomware Response Guide",
                "description": "Reduce ransomware risk and prepare a practical recovery path.",
                "duration": "10 min read",
                "url": "https://www.cisa.gov/stopransomware",
                "takeaways": [
                    "Keep offline or immutable backups for the data that matters most.",
                    "Know who can isolate devices and preserve evidence quickly.",
                    "Practice recovery before an incident turns into panic.",
                ],
                "bestFor": "Incident response plans and business continuity reviews.",
                "nextSteps": [
                    "Validate backup restoration",
                    "Document escalation contacts",
                    "Review device isolation steps",
                ],
            },
            {
                "id": "network-video",
                "icon": "Video",
                "type": "Video",
                "topic": "Network",
                "audience": "Home offices",
                "priority": "Practical",
                "title": "Network Hardening Guide",
                "description": "Practical steps for securing Wi-Fi and connected devices.",
                "duration": "15 min",
                "url": "https://www.youtube.com/results?search_query=secure+home+network+cybersecurity",
                "takeaways": [
                    "Use WPA3 or the strongest mode your router supports.",
                    "Separate guest and work devices from sensitive systems.",
                    "Patch routers and IoT devices instead of leaving them stale.",
                ],
                "bestFor": "Remote work setups and shared home networks.",
                "nextSteps": [
                    "Change the default router password",
                    "Update firmware",
                    "Remove unused connected devices",
                ],
            },
            {
                "id": "social-guide",
                "icon": "BookOpen",
                "type": "Guide",
                "topic": "Threats",
                "audience": "Business users",
                "priority": "High leverage",
                "title": "Social Engineering Guide",
                "description": "How to identify manipulation and protect sensitive processes.",
                "duration": "7 min read",
                "url": "https://www.cisa.gov/news-events/news/avoiding-social-engineering-and-phishing-attacks",
                "takeaways": [
                    "Validate unusual requests through a separate trusted channel.",
                    "Slow down when someone pushes urgency or secrecy.",
                    "Protect payment, credential, and approval workflows carefully.",
                ],
                "bestFor": "Finance, HR, support, and executive assistants.",
                "nextSteps": [
                    "Add call-back verification",
                    "Review payment approval steps",
                    "Teach escalation paths for suspicious requests",
                ],
            },
        ],
        "downloads": [
            {
                "id": "checklist",
                "title": "Security Awareness Checklist",
                "description": "Daily security practices checklist",
                "fileMeta": "PDF | generated instantly",
                "sections": [
                    "Use unique passwords and a password manager.",
                    "Turn on MFA for email, banking, admin, and cloud accounts.",
                    "Verify sender identity before opening links or attachments.",
                    "Keep operating systems, browsers, and apps updated.",
                    "Back up important files and test recovery periodically.",
                ],
            },
            {
                "id": "incident-plan",
                "title": "Incident Response Plan Template",
                "description": "Template for handling security incidents",
                "fileMeta": "PDF | generated instantly",
                "sections": [
                    "Identify the affected asset, user, account, and timestamp.",
                    "Preserve logs, screenshots, alerts, and suspicious files.",
                    "Contain the incident by disabling accounts or isolating devices.",
                    "Notify the correct owner, manager, or security contact.",
                    "Document root cause, impact, remediation, and lessons learned.",
                ],
            },
            {
                "id": "password-managers",
                "title": "Password Manager Comparison",
                "description": "Compare popular password managers",
                "fileMeta": "PDF | generated instantly",
                "sections": [
                    "Prefer managers with strong encryption and independent audits.",
                    "Check MFA support, recovery options, and device sync controls.",
                    "Use sharing features only for team-approved secrets.",
                    "Review breach alerts and password health dashboards monthly.",
                    "Export recovery codes and store them securely offline.",
                ],
            },
        ],
    }
