const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const MARGIN_X = 44;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN_X * 2;
const TOP_Y = 604;
const BOTTOM_Y = 58;

const palette = {
  ink: '#10152f',
  muted: '#56617d',
  paper: '#f4f7ff',
  panel: '#ffffff',
  line: '#dce3ff',
  indigo: '#7c6cff',
  violet: '#9b8cff',
  cyan: '#00c2ff',
  mint: '#25c799',
  amber: '#ffb347',
  red: '#ff5f6d',
  navy: '#070a19',
  navySoft: '#111735',
};

const severityColors = {
  Critical: '#ff4d67',
  High: '#ff8b3d',
  Medium: '#ffcc4d',
  Low: '#25c799',
  Info: '#00c2ff',
  Success: '#25c799',
};

const escapePdfText = (value) => String(value ?? '')
  .replace(/[^\x20-\x7E]/g, '')
  .replace(/\\/g, '\\\\')
  .replace(/\(/g, '\\(')
  .replace(/\)/g, '\\)');

const hexToRgb = (hex) => {
  const normalized = String(hex || '#ffffff').replace('#', '');
  const value = normalized.length === 3
    ? normalized.split('').map((char) => char + char).join('')
    : normalized.padEnd(6, '0').slice(0, 6);

  return [
    parseInt(value.slice(0, 2), 16) / 255,
    parseInt(value.slice(2, 4), 16) / 255,
    parseInt(value.slice(4, 6), 16) / 255,
  ];
};

const rgb = (hex, mode = 'rg') => `${hexToRgb(hex).map((item) => item.toFixed(3)).join(' ')} ${mode}`;

const compactText = (value, maxLength = 96) => {
  const normalized = String(value ?? '').replace(/\s+/g, ' ').trim();
  return normalized.length > maxLength ? `${normalized.slice(0, maxLength - 3)}...` : normalized;
};

const wrapText = (value, maxLength = 84) => {
  const words = String(value || '').replace(/\s+/g, ' ').trim().split(' ').filter(Boolean);
  const lines = [];
  let current = '';

  for (const word of words) {
    const safeWord = word.length > maxLength ? `${word.slice(0, maxLength - 1)}-` : word;
    const next = current ? `${current} ${safeWord}` : safeWord;
    if (next.length > maxLength && current) {
      lines.push(current);
      current = safeWord;
      continue;
    }
    current = next;
  }

  if (current) {
    lines.push(current);
  }

  return lines.length ? lines : [''];
};

const textCommand = (text, x, y, options = {}) => {
  const {
    font = 'F1',
    size = 11,
    color = '#e7e9ff',
  } = options;

  return [
    'BT',
    rgb(color, 'rg'),
    `/${font} ${size} Tf`,
    `${x} ${y} Td (${escapePdfText(text)}) Tj`,
    'ET',
  ].join('\n');
};

const rectCommand = (x, y, width, height, fill, stroke = null, strokeWidth = 1) => {
  const commands = ['q', rgb(fill, 'rg')];
  if (stroke) {
    commands.push(rgb(stroke, 'RG'));
    commands.push(`${strokeWidth} w`);
    commands.push(`${x} ${y} ${width} ${height} re B`);
  } else {
    commands.push(`${x} ${y} ${width} ${height} re f`);
  }
  commands.push('Q');
  return commands.join('\n');
};

const lineCommand = (x1, y1, x2, y2, color = palette.line, width = 1) => [
  'q',
  rgb(color, 'RG'),
  `${width} w`,
  `${x1} ${y1} m`,
  `${x2} ${y2} l`,
  'S',
  'Q',
].join('\n');

const shieldLogoCommand = (x, y, size = 42) => {
  const scale = size / 42;
  return [
    'q',
    rgb(palette.indigo, 'rg'),
    `${x} ${y} ${size} ${size} re f`,
    rgb('#ffffff', 'RG'),
    `${2.2 * scale} w`,
    `${x + 21 * scale} ${y + 34 * scale} m`,
    `${x + 10 * scale} ${y + 29 * scale} l`,
    `${x + 10 * scale} ${y + 18 * scale} l`,
    `${x + 21 * scale} ${y + 8 * scale} l`,
    `${x + 32 * scale} ${y + 18 * scale} l`,
    `${x + 32 * scale} ${y + 29 * scale} l`,
    'h S',
    `${x + 16 * scale} ${y + 21 * scale} m`,
    `${x + 20 * scale} ${y + 16 * scale} l`,
    `${x + 27 * scale} ${y + 24 * scale} l`,
    'S',
    rgb(palette.mint, 'RG'),
    `${x + 27 * scale} ${y + 9 * scale} m`,
    `${x + 36 * scale} ${y + 9 * scale} l`,
    'S',
    'Q',
  ].join('\n');
};

const heroCommands = ({ title, subtitle, eyebrow, generatedAt, classification }) => {
  const generated = generatedAt || new Date().toLocaleString('en-US');
  const subtitleLines = wrapText(subtitle || 'Security intelligence generated by Threat Hunters.', 76).slice(0, 3);

  return [
    rectCommand(0, 0, PAGE_WIDTH, PAGE_HEIGHT, palette.paper),
    rectCommand(0, 642, PAGE_WIDTH, 150, palette.navy),
    rectCommand(0, 642, PAGE_WIDTH, 8, palette.indigo),
    rectCommand(0, 650, 168, 142, '#0d1230'),
    rectCommand(400, 686, 192, 70, '#121a3c', '#303a73'),
    rectCommand(430, 716, 128, 6, palette.cyan),
    rectCommand(452, 704, 96, 5, palette.indigo),
    rectCommand(474, 692, 64, 4, palette.mint),
    lineCommand(360, 778, 594, 656, '#293462', 1.2),
    lineCommand(392, 790, 612, 708, '#1f2a55', 1),
    lineCommand(34, 656, 178, 790, '#1f2a55', 1),
    shieldLogoCommand(MARGIN_X, 722, 42),
    textCommand('Threat Hunters', 96, 748, { font: 'F2', size: 18, color: '#ffffff' }),
    textCommand(eyebrow || 'Security Report', 96, 729, { size: 9, color: '#aeb8ff' }),
    textCommand(compactText(classification || 'CONFIDENTIAL INTELLIGENCE', 34), 420, 735, {
      font: 'F2',
      size: 9,
      color: '#ffffff',
    }),
    textCommand('Generated', 420, 717, { size: 8, color: '#aeb8ff' }),
    textCommand(compactText(generated, 26), 420, 702, { font: 'F2', size: 10, color: '#ffffff' }),
    textCommand(compactText(title || 'Security Report', 62), MARGIN_X, 604, {
      font: 'F2',
      size: 23,
      color: palette.ink,
    }),
    ...subtitleLines.map((line, index) => (
      textCommand(line, MARGIN_X, 582 - index * 15, { size: 10.5, color: palette.muted })
    )),
  ].join('\n');
};

const footerCommands = (pageNumber, pageCount) => [
  rectCommand(MARGIN_X, 37, CONTENT_WIDTH, 1, palette.line),
  textCommand('Threat Hunters Security Intelligence', MARGIN_X, 22, { size: 8.5, color: palette.muted }),
  textCommand('Actionable findings | Evidence | Remediation guidance', 228, 22, { size: 8.5, color: '#6f7892' }),
  textCommand(`Page ${pageNumber} of ${pageCount}`, PAGE_WIDTH - 102, 22, { size: 8.5, color: palette.muted }),
].join('\n');

const createPage = (pageNumber, pageCount, bodyCommands, headerOptions = {}) => [
  heroCommands(headerOptions),
  bodyCommands.join('\n'),
  footerCommands(pageNumber, pageCount),
].join('\n');

const metricTone = (metric) => metric.accent || metric.valueColor || palette.indigo;

export const buildBrandedPdfBlob = ({
  title,
  subtitle,
  eyebrow = 'Security Report',
  generatedAt,
  classification = 'CONFIDENTIAL INTELLIGENCE',
  metrics = [],
  sections = [],
}) => {
  const rawPages = [];
  let y = TOP_Y - 78;
  let body = [];

  const pushPage = () => {
    rawPages.push(body);
    body = [];
    y = TOP_Y - 78;
  };

  const ensureSpace = (height) => {
    if (y - height < BOTTOM_Y) {
      pushPage();
    }
  };

  const addMetricGrid = () => {
    const safeMetrics = metrics.filter(Boolean).slice(0, 6);
    if (!safeMetrics.length) return;

    const columns = safeMetrics.length > 4 ? 3 : Math.min(safeMetrics.length, 4);
    const gap = 12;
    const cardWidth = (CONTENT_WIDTH - gap * (columns - 1)) / columns;
    const cardHeight = 64;
    const rows = Math.ceil(safeMetrics.length / columns);

    ensureSpace(rows * cardHeight + (rows - 1) * 12 + 24);

    safeMetrics.forEach((metric, index) => {
      const row = Math.floor(index / columns);
      const column = index % columns;
      const x = MARGIN_X + column * (cardWidth + gap);
      const top = y - row * (cardHeight + 12);
      const accent = metricTone(metric);

      body.push(rectCommand(x, top - cardHeight, cardWidth, cardHeight, metric.fill || palette.panel, metric.stroke || palette.line));
      body.push(rectCommand(x, top - 6, cardWidth, 6, accent));
      body.push(textCommand(compactText(metric.label, 24).toUpperCase(), x + 12, top - 24, {
        size: 7.5,
        color: metric.labelColor || '#727b95',
      }));
      body.push(textCommand(compactText(metric.value, 18), x + 12, top - 47, {
        font: 'F2',
        size: 17,
        color: metric.valueColor || palette.ink,
      }));
      if (metric.hint) {
        body.push(textCommand(compactText(metric.hint, 28), x + 12, top - 58, { size: 7.5, color: '#7a849d' }));
      }
    });

    y -= rows * cardHeight + (rows - 1) * 12 + 24;
  };

  const drawSectionHeader = (section, sectionIndex) => {
    const accent = section.accent || palette.indigo;
    ensureSpace(50);
    body.push(rectCommand(MARGIN_X, y - 34, CONTENT_WIDTH, 38, palette.panel, palette.line));
    body.push(rectCommand(MARGIN_X, y - 34, 7, 38, accent));
    body.push(textCommand(compactText(section.kicker || `Section ${sectionIndex + 1}`, 34).toUpperCase(), MARGIN_X + 18, y - 11, {
      size: 7.5,
      color: accent,
    }));
    body.push(textCommand(compactText(section.title || `Section ${sectionIndex + 1}`, 58), MARGIN_X + 18, y - 27, {
      font: 'F2',
      size: 14,
      color: palette.ink,
    }));
    y -= 50;
  };

  const addParagraph = (text, accent = palette.indigo) => {
    if (!text) return;
    const lines = wrapText(text, 94);
    ensureSpace(lines.length * 14 + 18);
    body.push(rectCommand(MARGIN_X, y - lines.length * 14 - 12, CONTENT_WIDTH, lines.length * 14 + 20, '#fbfcff', '#e8edff'));
    body.push(rectCommand(MARGIN_X, y - lines.length * 14 - 12, 4, lines.length * 14 + 20, accent));
    lines.forEach((line, index) => {
      body.push(textCommand(line, MARGIN_X + 14, y - index * 14, { size: 10, color: palette.muted }));
    });
    y -= lines.length * 14 + 28;
  };

  const addBullet = (item, accent = palette.indigo) => {
    const text = typeof item === 'string'
      ? item
      : `${item.title || item.label || 'Insight'}${item.detail ? ` - ${item.detail}` : item.body ? ` - ${item.body}` : ''}`;
    const lines = wrapText(text, 88);
    const height = Math.max(34, lines.length * 13 + 18);

    ensureSpace(height + 8);
    body.push(rectCommand(MARGIN_X, y - height, CONTENT_WIDTH, height, '#ffffff', '#e5ebff'));
    body.push(rectCommand(MARGIN_X + 10, y - 22, 10, 10, item?.tone ? severityColors[item.tone] || accent : accent));
    lines.forEach((line, index) => {
      body.push(textCommand(line, MARGIN_X + 30, y - 18 - index * 13, { size: 9.5, color: '#303a57' }));
    });
    y -= height + 8;
  };

  const addRow = (row, accent = palette.indigo) => {
    const toneColor = severityColors[row.tone] || row.accent || accent;
    const detailLines = wrapText(row.detail || row.description || '', 66).slice(0, 2);
    const height = detailLines.length ? 52 : 38;

    ensureSpace(height + 8);
    body.push(rectCommand(MARGIN_X, y - height, CONTENT_WIDTH, height, '#ffffff', '#e5ebff'));
    body.push(rectCommand(MARGIN_X, y - height, 5, height, toneColor));
    body.push(textCommand(compactText(row.label || row.title || 'Signal', 42), MARGIN_X + 14, y - 18, {
      font: 'F2',
      size: 10,
      color: palette.ink,
    }));
    body.push(textCommand(compactText(row.value ?? row.status ?? '', 24), PAGE_WIDTH - 160, y - 18, {
      font: 'F2',
      size: 10,
      color: toneColor,
    }));
    detailLines.forEach((line, index) => {
      body.push(textCommand(line, MARGIN_X + 14, y - 34 - index * 12, { size: 8.8, color: palette.muted }));
    });
    y -= height + 8;
  };

  const addSeverityBars = (counts = {}) => {
    const labels = ['Critical', 'High', 'Medium', 'Low', 'Info'];
    const max = Math.max(...labels.map((label) => Number(counts[label] || 0)), 1);
    ensureSpace(104);
    body.push(rectCommand(MARGIN_X, y - 94, CONTENT_WIDTH, 94, '#ffffff', '#e5ebff'));
    labels.forEach((label, index) => {
      const value = Number(counts[label] || 0);
      const rowY = y - 18 - index * 16;
      const barWidth = Math.max(8, (value / max) * 248);
      body.push(textCommand(label, MARGIN_X + 14, rowY, { size: 8.5, color: palette.muted }));
      body.push(rectCommand(MARGIN_X + 88, rowY - 2, 260, 7, '#edf1ff'));
      body.push(rectCommand(MARGIN_X + 88, rowY - 2, barWidth, 7, severityColors[label] || palette.indigo));
      body.push(textCommand(String(value), MARGIN_X + 362, rowY, { font: 'F2', size: 8.5, color: palette.ink }));
    });
    y -= 110;
  };

  addMetricGrid();

  sections.filter(Boolean).forEach((section, sectionIndex) => {
    drawSectionHeader(section, sectionIndex);
    addParagraph(section.body, section.accent);

    if (section.severityCounts) {
      addSeverityBars(section.severityCounts);
    }

    if (Array.isArray(section.rows)) {
      section.rows.forEach((row) => addRow(row, section.accent));
    }

    if (Array.isArray(section.items)) {
      section.items.forEach((item) => addBullet(item, section.accent));
    }

    y -= 8;
  });

  if (!rawPages.length || body.length) {
    pushPage();
  }

  const pages = rawPages.map((pageBody, index) => createPage(index + 1, rawPages.length, pageBody, {
    title,
    subtitle,
    eyebrow,
    generatedAt,
    classification,
  }));

  const objects = [
    `1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n`,
    `2 0 obj\n<< /Type /Pages /Kids [${pages.map((_, index) => `${3 + index} 0 R`).join(' ')}] /Count ${pages.length} >>\nendobj\n`,
    ...pages.map((page, index) => {
      const pageObjectId = 3 + index;
      const contentObjectId = 3 + pages.length + index;
      return `${pageObjectId} 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 ${3 + pages.length * 2} 0 R /F2 ${4 + pages.length * 2} 0 R >> >> /Contents ${contentObjectId} 0 R >>\nendobj\n`;
    }),
    ...pages.map((page, index) => {
      const contentObjectId = 3 + pages.length + index;
      return `${contentObjectId} 0 obj\n<< /Length ${page.length} >>\nstream\n${page}\nendstream\nendobj\n`;
    }),
    `${3 + pages.length * 2} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n`,
    `${4 + pages.length * 2} 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj\n`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object) => {
    offsets.push(pdf.length);
    pdf += object;
  });

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  for (let index = 1; index <= objects.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return new Blob([pdf], { type: 'application/pdf' });
};

export const downloadPdfBlob = (blob, filename) => {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
};
